### ISSUE TITLE
multi page add all srihash?can include hash  split?

### ISSUE THREAD

**Issue by WilsonLiu95** [waysact/webpack-subresource-integrity#100]
I use webpack to build multi web.I want to inline the runtime js file.So I split runtime multi.but the sri include all. can config it?

**Comment by jscheid** [comment]
Sorry, I don't understand what the problem is. Could you make an example repository?

**Comment by jscheid** [comment]
I'm going to close this because I don't know what to do here, but feel free to reopen with a link to a repository that demonstrates the problem and I'm happy to take another look.
