### ISSUE TITLE
Use with create-react-app?

### ISSUE THREAD

**Issue by gavinr** [waysact/webpack-subresource-integrity#112]
I know there [was](https://github.com/facebook/create-react-app/pull/1176) [reverted] and [still is](https://github.com/facebook/create-react-app/issues/7006) an effort to get this officially working with [create-react-app](https://github.com/facebook/create-react-app), but in the mean-time, what is the best workaround to get this working on the built version of the app that create-react-app generates?

**Comment by gavinr** [comment]
One workaround is to use [eject](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject):

### 1. Run:
```
npm run eject
npm install webpack-subresource-integrity
```

### 2. Modify `webpack.config.js`:
https://github.com/facebook/create-react-app/pull/1176/files

### 3. Run `npm run build`
Your `build/index.html` file should now have `integrity="..."` tags.

**Comment by jscheid** [comment]
Yes, I'm not aware of another way to use this plugin together with CRA. For the time being you'll have to eject.
