### ISSUE TITLE
Compressed files - integrity problem

### ISSUE THREAD

**Issue by emzet** [waysact/webpack-subresource-integrity#125]
Hi, in my **Angular 9** app I'm using [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) for extending internal **webpack configuration**, because I want to pre-built also **gzip** and **brotli** files with this plugin [
compression-webpack-plugin](https://github.com/webpack-contrib/compression-webpack-plugin). Everything works fine, gzipped and brotlied files are ok. The problem is when I try to build Angular application with `--subresource-integrity` flag. Adding this flag it simply enables this **webpack-subresource-integrity** plugin under the hood in **Angular CLI** and outputs **integrity** attributes for **script** and **style** elements in **index.html**. 

Then the problem is that this plugin computes integrity hashes from original files but not compressed ones. If browser supports gzip or brotli encoding, then server sent those static assets (js, css, ...) compressed instead of original one so the problem is that hash does not match. The question is, if it is possible to solve it somehow. As you can see in [this](https://github.com/tc39/proposal-binary-ast/issues/48#issuecomment-419356000) proposal, there is possibility to use **multiple values** of same hash. So is it possible to collaborate with **compression-webpack-plugin**, so this plugin outputs all possible hashes for 1 file (original, gzipped, brotli, etc.). Then from what is written [here](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) and in proposal, seems that browsers should match only one from those and everything should work. Thanks.

**Comment by jscheid** [comment]
> Then the problem is that this plugin computes integrity hashes from original files but not compressed ones. If browser supports gzip or brotli encoding, then server sent those static assets (js, css, ...) compressed instead of original one so the problem is that hash does not match.

I suspect you have a different problem if the hash doesn't match, since browsers [compute the hash for the uncompressed asset](https://www.w3.org/TR/SRI/#apply-algorithm-to-response). We've been using SRI together with compression (with just a single hash value computed from the uncompressed asset) for years without problems, and I'm sure many/most other people do too.

It would be best if you could make a repository to demonstrate the issue, preferably just using this plugin and compression-webpack-plugin (without Angular).

**Comment by jscheid** [comment]
Here's a simple [demo with compression-webpack-plugin](https://github.com/jscheid/wsi-issue-125) - works fine.

**Comment by jscheid** [comment]
I'm closing this, feel free to reopen but if you do, please provide a demo or test case.
