### ISSUE TITLE
WARNING in webpack-subresource-integrity:

### ISSUE THREAD

**Issue by Emanuel-Gill** [waysact/webpack-subresource-integrity#128]
Cannot determine asset for chunk scripts, computed="undefined", available=scripts.b84d85e55bd4a8995fb5.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new

**Comment by jscheid** [comment]
Thanks, this happens with older angular-cli versions which depend on an old version of this plugin. Upgrading to angular-cli 10 should fix it.

Closing as a duplicate of #104
