### ISSUE TITLE
Error of hash lookup for dynamic chunks 

### ISSUE THREAD

**Issue by li-xianfeng** [waysact/webpack-subresource-integrity#135]
webpack-subresource-integrity@1.5.1
webpack@5.3.2

It's fail to lookup hash value for dynamic chunk when the chunk id is not digit.
![error-key](https://user-images.githubusercontent.com/8556095/98104394-59e35180-1ed1-11eb-898d-bf60fe75cc70.png)

![webpack-config](https://user-images.githubusercontent.com/8556095/98104785-e7bf3c80-1ed1-11eb-8ed6-ca456f49c092.png)

**Comment by jscheid** [comment]
Thanks for reporting this. Released in 1.5.2 🚢
