### ISSUE TITLE
Issue with Terser Plugin using banner

### ISSUE THREAD

**Issue by edwinbadillo** [waysact/webpack-subresource-integrity#139]
It seems the SRI value is being generated before the terser plugin adds the banner.
Following standard properties to separate license copy as per webpack documentation.
https://webpack.js.org/plugins/terser-webpack-plugin/#banner

webpack-subresource-integrity 1.5.2
terser-webpack-plugin 5.0.3
webpack 5.4.0

**Comment by jscheid** [comment]
Thanks for the bug report. This is going to be fixed in the upcoming 5.0 branch. I'm planning to release a first alpha version in the course of next week.

**Comment by jscheid** [comment]
I've now released version 5.0.0-alpha.1, see https://github.com/waysact/webpack-subresource-integrity/issues/144

@edwinbadillo there's a test case for your issue so it should work for you: https://github.com/waysact/webpack-subresource-integrity/tree/next/examples/terser-banner

Closing this, feel free to reopen if there's still a problem.
