### ISSUE TITLE
Doesn't work with webpack 5's realContentHash

### ISSUE THREAD

**Issue by zlk89** [waysact/webpack-subresource-integrity#142]
Reproducible sandbox: https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-9lnjm?file=/src/template.html
If you open console, you will see the error saying the integrity is wrong.
[if the sandbox doesn't load, just open a new terminal and run `yarn start` and refresh the built-in browser]

To reproduce, you need to enable:
- source map
- optimization.realContentHash = true
- use contenthash in output filename

**Comment by jscheid** [comment]
Sorry, we don't have support for HWP 5 yet. (You should have seen a [warning to that effect](https://github.com/waysact/webpack-subresource-integrity/blob/4c965fcbed636177da3c98173b294f38806cac92/package.json#L79)). Planning to release a new compatible version once [this](https://github.com/jantimon/html-webpack-plugin/issues/1554#issuecomment-748033522) is sorted out.
