### ISSUE TITLE
RFC: Release 5.0

### ISSUE THREAD

**Issue by jscheid** [waysact/webpack-subresource-integrity#144]
We're preparing to release a new major version 5.0, skipping major versions 2-4. Development is taking place in the [`next` branch](https://github.com/waysact/webpack-subresource-integrity/tree/next).

Read the [migration instructions](https://github.com/waysact/webpack-subresource-integrity/blob/next/MIGRATE-v1-to-v5.md) and see [early releases](https://github.com/waysact/webpack-subresource-integrity/releases) with a description of changes.

Please give it a go and leave a thumbs-up here if it's working well for you, or create a new issue if it isn't. Comments and suggestions are welcome.

**Comment by StephanBijzitter** [comment]
Thanks for this issue, and especially thanks for the great release notes on the alpha versions. Worked first try :-)

**Comment by mfinelli** [comment]
Any idea when we might see a final v5 release? I've been using the v5 alpha for a few months now without issue.

**Comment by jscheid** [comment]
@mfinelli yes, it's overdue. I'll try to find the time and finalize 5.0.0 soon, watch this space.

**Comment by KiranEarle** [comment]
Hi all, any updates on when this is a full fledged version, having trouble convincing the business to move to webpack 5 with this being a full version?

**Comment by jscheid** [comment]
I'm going to try and get to this next week.

**Comment by jarrett-confrey** [comment]
@jscheid the alpha is working well for me. im looking forward to a non alpha version when you get a chance 😄

**Comment by jscheid** [comment]
Thanks all for your patience, it's been a busy time for me but there's going to be a new release later this week, and a 5.0 release in the not too distant future.

**Comment by jscheid** [comment]
5.0.0-rc.1 is out now, let me know how you go with it. I'm planning to follow it up with a 5.0.0 release in the near future.

**Comment by jscheid** [comment]
5.0.0 release is out! 🎉 Thanks all for your feedback and your patience.
