### ISSUE TITLE
Usage without html-webpack-plugin?

### ISSUE THREAD

**Issue by ZebraFlesh** [waysact/webpack-subresource-integrity#145]
I'm struggling with how to use this without html-webpack-plugin. Given the following list of plugins in my webpack.config.js:

```js
  plugins: [
    new CleanWebpackPlugin(),
    new MiniCssExtractPlugin({
      filename: '[name].[contenthash].min.css'
    }),
    new SriPlugin({
      hashFuncNames: ['sha512']
    }),
    // new HtmlWebpackPlugin(),
    {
        compiler.hooks.done.tap('OutputIntegrity', (stats) => {
          const json = stats.toJson();
          for (const asset of json.assets) {
            if (asset.name.match(/.*\.(css|js)/)) {
              console.log(asset.name, asset.integrity);
            }
          }
        });
      }
    }
  ],
```

All of the `asset.integrity` values are `undefined` (because the property doesn't exist on the object). However, when I add HtmlWebpackPlugin to the list of plugins, I definitely get `integrity` values. So this plugin is working, but I can't seem to locate the info in the stats object.

Environment:
node: 12.19.0
webpack: 5.11.1
webpack-subresource-integrity: 1.5.2

**Comment by jscheid** [comment]
I'll try and take a look soon. In the meantime you could see if you have more luck with version `5.0.0-alpha.1`? You'll have to upgrade webpack to 5.12 or newer as well.

**Comment by ZebraFlesh** [comment]
`5.0.0-alpha.1` successfully produces hashes 🎉. Unfortunately, I was looking specifically for sha512 hashes. [Here's a good explainer on why you should used sha512 if you're using only a single hash](https://stackoverflow.com/questions/52101501/whats-the-best-sri-hash-size/52102596#52102596).

**Comment by jscheid** [comment]
You can still [configure which function to use](https://github.com/waysact/webpack-subresource-integrity/tree/next/webpack-subresource-integrity#hashfuncnames
), as before. Does that not work?

**Comment by ZebraFlesh** [comment]
I _completely_ missed that and thought it was locked down sha384 in the v5 line. That option works, thank you!
