### ISSUE TITLE
Cannot import plugin with `@next` release

### ISSUE THREAD

**Issue by willdurand** [waysact/webpack-subresource-integrity#146]
Hey, I pulled the `@next` release (alpha-1) in my project and it's not possible to use the following import line anymore:

```
import SriPlugin from 'webpack-subresource-integrity';
```

The error I get is:

```
TypeError: _webpackSubresourceIntegrity.default is not a constructor
```

Instead, I have to use:

```
import { SubresourceIntegrityPlugin } from 'webpack-subresource-integrity';
```

**Comment by jscheid** [comment]
Yes, that's on purpose, there's some more info here: https://github.com/waysact/webpack-subresource-integrity/blob/next/MIGRATE-v1-to-v5.md#named-export-subresourceintegrityplugin

**Comment by willdurand** [comment]
aww sorry about that, I missed that md file 🤦

**Comment by jscheid** [comment]
No problem, it needs a more prominent link. I'll push a change to the readme on master.
