### ISSUE TITLE
How to access integrity value for non chunks within a HtmlWebpackPlugin template?

### ISSUE THREAD

**Issue by Chris3773** [waysact/webpack-subresource-integrity#151]
I have a loader to split out css files so I can load them at runtime. My plan was within the HtmlWebpackPlugin template add a global with a map to the css file path and the integrity value. Then I could map the integrity value to load at runtime. The problem is when I look on the `compilation` object within the HtmlWebpackPlugin template I only see the integrity values for the chunks under the `contenthash` object. I don't see a way to access the integrity value for any other asset.

Is there a way to access the integrity value of all assets within the HtmlWebpackPlugin template?

webpack version: 5.22.0
webpack-subresource-integrity: 5.0.0-alpha.3

**Comment by jscheid** [comment]
Is there a reason you can't use normal code splitting for lazy-loading your CSS, such as with [mini-css-extract-plugin](https://webpack.js.org/plugins/mini-css-extract-plugin/)?

**Comment by Chris3773** [comment]
Lazy loading with mini-css-extract-plugin creates a chunk that needs to load before loading the css file. I was trying to avoid the extra loading of a file that only had the path in the chunk.

**Comment by jscheid** [comment]
Does it really matter with HTTP 2? 

Anyway, to answer your original question: if it's not a chunk, this plugin won't calculate integrity for it in the first place. If you make it a chunk then you can access the integrity value on the `compilation.assets` object.

If it's an asset and not a chunk, which I suppose would be possible like eg. Webpack does for images, then I'm not 100% sure. As you're probably aware, the code that calculates the actual checksum is only a small part of the code in this plugin and would be trivial to replicate, but I'd be happy to find a way for you to reuse it more easily if that's what you're after. Is your plugin going to be open source?

**Comment by Chris3773** [comment]
I'm not creating a plugin as I can get what I need from the asset module that was added in webpack 5. The logic for when the sytlesheets are added are also controlled by the app.

This is the loader setup what I have that is splitting out the files.
```
{
  test: /\.s[ac]ss$/,
  include: [join(__dirname, 'src/app/theme')],
  type: 'asset/resource',
  use: [
    {
        loader: 'extract-loader'
    },
    {
        loader: 'css-loader'
    },
    {
        loader: 'sass-loader'
    }
  ]
  }
```

The hack I came up with is to create and add the integrity value as a query param on filename creation. However with when the hash is created it limits me from using css minimizer and requires another loader to minimize.

```
{
  test: /\.s[ac]ss$/,
  include: [join(__dirname, 'src/app/theme')],
  type: 'asset/resource',
  generator: {
    filename: (pathData: { module }) => {
      if (isDebug) {
          return '[name].[hash:4].theme.css';
      }
      else {
          const hash = createHash('sha384')
              .update(pathData.module.originalSource()?.source() || '')
              .digest('base64');
          return `[contenthash].theme.css?sha384-${hash}`;
      }
    }
  }
}
```

I wanted to try and avoid creating another plugin when this plugin had all of the correct hooks in place for creating the hash with the correct value. Is it possible to add the integrity value to all of the assets so it can be accessed on `compilation` object?

**Comment by jscheid** [comment]
I see, let me take a closer look. Could you put up a test repo?

**Comment by jscheid** [comment]
@Chris3773 if you still wanted me to look into it, I need you to put up a small sample repository that demonstrates the issue. Feel free to reopen this once you find the time to do that.
