### ISSUE TITLE
Adding integrity to a chunk

### ISSUE THREAD

**Issue by Darren-Ivey** [waysact/webpack-subresource-integrity#157]
I want to add sri to my scripts that are using the files.chunks. Is this possible?

A snippet of my code is below

```
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script
          src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"
  >
  </script>
<% } %>
```

**Comment by jscheid** [comment]
What are you trying to achieve? The normal way chunks are used in Webpack is through lazy-loading, which this plug-in supports transparently.

**Comment by Darren-Ivey** [comment]
Thank you for getting back to me so quickly. I know my setup has html-webpack-plugin with inject: false and I want to add integrity to the script. The example in the Readme shows how to do this with htmlWebpackPlugin.files, but I am not sure how to achieve it with htmlWebpackPlugin.files.chunks. I imagine it would be something like this?

```
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script
     src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"
     integrity="<%= htmlWebpackPlugin.files.jsIntegrity[chunk] %>"
     crossorigin="<%= webpackConfig.output.crossOriginLoading %>"
  >
  </script>
<% } %>
```

**Comment by jscheid** [comment]
Why do you want to use `files.chunks` and not just `files`?

**Comment by jscheid** [comment]
Closing due to reporter timeout.
