### ISSUE TITLE
Wrong integrity hashes injected to scripts through HtmlWebpackPlugin v5+

### ISSUE THREAD

**Issue by oleksandrsydorenko** [waysact/webpack-subresource-integrity#158]
## Current behaviour

Plugin computes hashes for incorrect chunk files names

<img width="251" alt="Screenshot 2021-04-28 at 17 32 18" src="https://user-images.githubusercontent.com/20060789/116421732-c8cdb180-a847-11eb-8a9d-498327d08d99.png">

instead of

<img width="722" alt="Screenshot 2021-04-28 at 17 32 33" src="https://user-images.githubusercontent.com/20060789/116421777-d2efb000-a847-11eb-9126-84914586adca.png">

Issue occurs only with HtmlWebpackPlugin v5+, for v4.5.1 and below it forks fine.

## Expected behaviour

Computed hashes should be correct

## Reproduction Example

https://github.com/oleksandrsydorenko/react-typescript-starter-kit

1. Upgrade html-webpack-plugin to the latest version (5.3.1)
2. Run `yarn build`
3. Run http server for `/dist` folder

**Comment by jscheid** [comment]
You're using version 1.5.2 which is incompatible with html-webpack-plugin version 5. Please try again using the `next` version (5.0.0-alpha.5) and let me know if this works, it should.

**Comment by oleksandrsydorenko** [comment]
With 5.0.0-alpha.5 version works fine, thanks!
