### ISSUE TITLE
Warning: webpack-subresource-integrity: Cannot determine asset for chunk 4953, computed="425936091ab94d4d8648.png", available=4953.d2f266edafb09b67e3c6.js. 

### ISSUE THREAD

**Issue by And2s** [waysact/webpack-subresource-integrity#159]
Angular 12.0.0 (no extra webpack config)

Many warnings like this on `ng build`:

```
Warning: webpack-subresource-integrity: Cannot determine asset for chunk 4953, computed="425936091ab94d4d8648.png", available=4953.d2f266edafb09b67e3c6.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new
```

I am using Webpack Asset Modules feature:
```
new URL('../images/car-door.png', import.meta.url)
```

**Comment by jscheid** [comment]
Which version of this plugin (`webpack-subresource-integrity`) are you using?

**Comment by jscheid** [comment]
Closing this. Feel free to reopen if you can provide more detail.

**Comment by And2s** [comment]
Using Angular 12.1.2 framework. It has `webpack-subresource-integrity` 1.5.2 

I import images using Webpack Asset Modules feature.

e.g.
`new URL('./images/bg.jpeg', import.meta.url).pathname`

All images seems successfully imported. Only these warnings appear.
