### ISSUE TITLE
Conflict with html-webpack-plugin - wrong hash being computed

### ISSUE THREAD

**Issue by themgoncalves** [waysact/webpack-subresource-integrity#164]
## Current behaviour 💣

After upgrading the `html-webpack-plugin` to `v5+`, somehow the assets are being manipulated in a way that it does not match the previously computed `integrity` hash anymore, outputing the following error on Browser's console:

> Failed to find a valid digest in the 'integrity' attribute for resource '<name>.bundle.js' with computed SHA-256 integrity 'pYpTWHH....'. The resource has been blocked.

The `Sub Resource Integrity` is of course computed by `webpack-subresource-integrity`.

## Expected behaviour ☀️

Keep assets as it was received.

### Reproduction Example 👾

```js
const path = require('path');
const SriPlugin = require('webpack-subresource-integrity');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  target: 'web',
  entry: {
    app: ['./src/application.tsx'],
  },
  output: {
    publicPath: '/',
    path: path.join(__dirname, './public'),
    filename: 'js/[name].bundle.js',
    chunkFilename: 'js/[name].chunk.js',
    crossOriginLoading: 'anonymous',
  },
  plugins: [
    new SriPlugin({
      hashFuncNames: ['sha256', 'sha384', 'sha512'],
      enabled: true,
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      inject: true,
      minify: {
        collapseWhitespace: true,
        preserveLineBreaks: false,
      },
    }),
  ],
};

```

## Environment 🖥

```
Node.js v14.17.3
darwin 20.5.0

NPM v6.14.13

Webpack v5.47.0
html-webpack-plugin v5
webpack-subresource-integrity v1.5.2
```

## Additional Infos

This issue also has been raised on [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin/issues/1668), which was recommend to open this issue here, most likely for using deprecated Webpack hooks.

**Comment by jscheid** [comment]
Using 5.0.0-rc.1 should fix this: https://github.com/waysact/webpack-subresource-integrity/tree/main/webpack-subresource-integrity#readme

**Comment by themgoncalves** [comment]
@jscheid indeed the `v5.0.0-rc.1` fixes this issue and for that, I'm closing this issue.
