### ISSUE TITLE
Upgraded from 1 -> 5 and now integrity value is not available in custom webpack plugin

### ISSUE THREAD

**Issue by jaslloyd** [waysact/webpack-subresource-integrity#180]
Hey we have been on v1 for a long time and we finally got around to updating to v5 and we noticed that integrity value is no longer available on the asset[filename]. We are using webpack 5, we are not using HtmlWebpackPlugin here is the sample of code of our webpack plugin:

```js
  apply = compiler => {
    compiler.hooks.emit.tapAsync('FileListPlugin', async ({ assets }, callback) => {
      Object.keys(assets).forEach(filename => {
        if (filename.match( /(vendor|runtime|index)\..*\.js(?!\.map)/)) {
          // as of v5 .integrity is now returning undefined.
          this.scripts += `loadScript('/${filename}', '${assets[filename].integrity}');`;
        }
      });

      // non important code here
      callback();
    });
  };
```

Any ideas of how we would get this .integrity value inside our custom plugin, I tried the 'done' hook but it wasn't available there either.

**Comment by jaslloyd** [comment]
@jscheid thanks for the quick response, it's interesting in the example and I can see that I can get it in the done hook. Do you know how I can access it in `emit` hook?

As the emit hook is not a stats parameter its a compilation hook. I tried `compilation.getAssets().forEach(({ info }) => console.log(info.contentHash[1]))`

which seems to be it but seems a little bit messy. I need it in the emit hook as I am outputting more custom assets there.

**Comment by jscheid** [comment]
There is `compilation.getStats().toJson()`, does that work?

**Comment by jaslloyd** [comment]
@jscheid Yeah so that did work I am going to put this here incase anybody else runs into this. 

```js
    compiler.hooks.thisCompilation.tap('MyPlugin', compilation => {
      compilation.hooks.processAssets.tap(
        {
          name: 'MyPlugin',
          stage: Compilation.PROCESS_ASSETS_STAGE_REPORT,
        },
        async () => {
          const { assets } = compilation.getStats().toJson();
          assets.forEach(({ name, integrity }) => {
            // do what you need to do
          });
          const newAssetCode = 'hello world' // whatever
          compilation.emitAsset('new asset.js', new sources.RawSource(newAssetCode));
        },
      );
    });
```

Going to close this thank you so much!
