### ISSUE TITLE
Feature request: supporting additional file types beyond CSS and JS

### ISSUE THREAD

**Issue by jayaddison** [waysact/webpack-subresource-integrity#208]
I'd like to use `webpack-subresource-integrity` to calculate integrity hashes for some dynamically-collected (albeit manually-configured) application dependency licensing information from a webpack configuration file, but at the moment (as I understand it?) only CSS and JS file types are supported.

Some naive initial code observations:

It looks like the `assetTypeIntegrityKeys` variable provides a mapping between the file extensions supported by `webpack-subresource-integrity` and a means to access the resulting integrity hashes from a webpack configuration.

Currently `css` and `js` are supported, which makes sense as those are the file extensions most frequently included as HTML `link` and `script` elements -- and those are the elements [described in the relevant W3 WebAppSec spec for subresource integrity](https://github.com/w3c/webappsec/blob/1eb5f9e49470661a3cb3a23455c3cbf7d2426095/specs/subresourceintegrity/spec.markdown?plain=1#L568-L609).

**Comment by jscheid** [comment]
If you want to protect non-JS, non-CSS content you have two options. The first option is to wrap your content in one of the supported file types, either as a comment or in the same way [file-loader](https://v4.webpack.js.org/loaders/file-loader/) works (i.e. by generating code that exports the content as a JS object.)

The second option is to keep your content as an asset in the same place (origin/server/permission scope) as your root HTML file. That's already a trusted place as it serves the SRI hashes.

Beyond that, without browser support this is not a feature we can implement even if we wanted to and so I'm going to close this. If you know something that I don't about how you would ask a browser to verify SRI for other file types, a PR adding this feature is welcome.

**Comment by jayaddison** [comment]
Thanks @jscheid - nope, I'm not aware of browser support for other file types, and the suggestion to host content within the same origin makes sense :+1:
