### ISSUE TITLE
Easy integration with html-webpack-plugin

### ISSUE THREAD

**Issue by Klathmon** [waysact/webpack-subresource-integrity#3]
Is there any easy way to integrate this into the [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin)?

I didn't want to go nuts implementing my own stuff to insert the hashes into the output html if there is an easier way.

**Comment by SPSpwetter** [comment]
Or with https://github.com/jaketrent/html-webpack-template?

**Comment by jscheid** [comment]
Hi, currently there is no integration with these packages and since we're not using them, no plans to implement any at the moment.

It sounds like a good fit though so if you want to go ahead and build integration I'd be happy to merge. Perhaps using their [event hooks](https://github.com/ampedandwired/html-webpack-plugin#events)?

**Comment by SPSpwetter** [comment]
Seems like it might be possible by tweaking their templates to pull the SRI info you're already creating? I may be working on this in a couple of weeks.

**Comment by SPSpwetter** [comment]
I got it working by turning off injection and adding: 

<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>" 
	integrity = "<%= compilation.assets[chunk+"."+htmlWebpackPlugin.files.chunks[chunk].hash+".bundle.js"].integrity %>"></script>
<% } %>

To my template.

**Comment by SPSpwetter** [comment]
FYI, still working on this. html-webpack-plugin would rather a write a hook to modify the HTML after the fact. I'm open to that, but its a little downstream of where i would like to do it, so we're going back and forth.
