### ISSUE TITLE
infinite loop in findDepChunks

### ISSUE THREAD

**Issue by hikirsch** [waysact/webpack-subresource-integrity#37]
Hi -

We have a fairly large project and when we include this plugin, we get a maximum callback error. I've traced it down do the findDepChunks. If I move the recursive call into the if check, it works. I think depending on how you have lazy loading modules you can get chunks that are dependent on other chunks therefore by moving the recursive call, it seems to fix and I'm able to see the desired results.

If this is correct, I can make a PR for this fix.

Thanks.

--Adam

EDIT: we are using webpack 2.2.1 (we ran ng eject from angular-cli and added this plugin)

**Comment by jscheid** [comment]
Hi Adam,

The existing tests still pass with this change, so it might be a good fix. However I'd prefer if we could add a failing test case first. Is there any chance you could boil it down to one?

**Comment by hikirsch** [comment]
@jscheid - it seems to be some sort of circular dependency issue but I am not able to recreate the issue in the test suite. i will continue to try.

**Comment by jscheid** [comment]
Never mind, I can reproduce. It works when A lazy-loads B and B lazy-loads A, but breaks when A->B, B->C, C->A. Going to release a fix soon, thanks for investigating!

**Comment by jscheid** [comment]
@hikirsch will probably have to wait until S3 is back up.

**Comment by hikirsch** [comment]
np - i've linked an updated version of this package with the change and i'm able to move forward for now. thanks for fixing so fast!

**Comment by hikirsch** [comment]
i just ran an npm install on this package again, i think you guys may have forgotten to up the version in the package.json.

**Comment by jscheid** [comment]
@hikirsch it's not published yet, just getting in a few more small improvements before releasing as 0.9.0. Should be ready in an hour or so. I'll comment here when it's out.

**Comment by jscheid** [comment]
@hikirsch published now as 0.9.0. I'm guessing you don't need compatibility with Webpack release candidates or Node 0.12, so I didn't bother backporting to 0.8. Can you give it a try and let me know if it works for you?

**Comment by hikirsch** [comment]
yes all good now thank you!!
