### ISSUE TITLE
Integration with `DLLPlugin`

### ISSUE THREAD

**Issue by leesiongchan** [waysact/webpack-subresource-integrity#51]
Or compatible with library like https://github.com/asfktz/autodll-webpack-plugin

**Comment by jscheid** [comment]
Hi, we're not using DLLPlugin but it sounds like a good feature for sure. Would you be interested in implementing it?

**Comment by jscheid** [comment]
This can now be done using [add-asset-html-webpack-plugin](https://github.com/SimenB/add-asset-html-webpack-plugin#add-a-dll-file-from-webpackdllplugin).

[Example here](https://github.com/waysact/webpack-subresource-integrity/tree/master/examples/dll-plugin).
