### ISSUE TITLE
Does not work with dynamic `import`

### ISSUE THREAD

**Issue by shane-tomlinson** [waysact/webpack-subresource-integrity#55]
The plugin works great with the `require.ensure` way of loading resources, but does not work with the new [dynamic `import`](https://webpack.js.org/guides/code-splitting/#dynamic-imports) loading method.

**Comment by jscheid** [comment]
I've made a test based on the code from your link, and it works fine:

https://github.com/jscheid/wsi-issue-55

Perhaps you're having the same problem as #53?

I'd like to again draw your attention to our guidelines for creating new issues: https://github.com/waysact/webpack-subresource-integrity/blob/master/CONTRIBUTING.md#issues

**Comment by jscheid** [comment]
I've just released a fix for #53 in v1.0.2, can you try again with that? In the meantime I'm going to close this, but feel free to reopen if the issue persists. I'll need some more information about your setup though.
