### ISSUE TITLE
Interaction with webpack-manifest-plugin

### ISSUE THREAD

**Issue by arthurjamain** [waysact/webpack-subresource-integrity#57]
Hey there,

I'm using https://github.com/danethurber/webpack-manifest-plugin in my project and it appears to be incompatible with this SRI plugin. Much sadness was had.

To be more precise :

When both plugins are enabled, the SRI plugin fails to replace the placeholder string with the actual SRI map in the anonymous chunks' bootstrap code. I've dug a bit (but not entirely yet), and it boils down to https://github.com/waysact/webpack-subresource-integrity/blob/master/index.js#L220 this yielding the chunk manifest instead of the intended source.
As a result, the chunk scripts are inserted with placeholder values in the `integrity=""` attributes.

I'm not sure if I should be filing this here or at webpack-manifest-plugin, but I thought I'd start here.

I actually need to solve this so I'm going to debug this a bit anyway. I'll keep you posted if something relevant comes up.

**Comment by jscheid** [comment]
Hi,

That is indeed a sad story :-)

I think here is a good place to start, what the other plugin does seems fairly harmless at first glance (add a new asset).

Thanks for digging, let me know what you can find out. If you get stuck I might find some time to take a look but probably not before next week. Good luck for now!

**Comment by jscheid** [comment]
> what the other plugin does seems fairly harmless at first glance (add a new asset)

On second thought, adding a new asset in the `emit` phase seems wonky. I can see that they need to add late in the process, at a point where the other assets are locked down, but `emit` is pretty much the very latest point and might be too late for our plugin to work correctly.

At this point this is all just conjecture, but I have a hunch that maybe (hopefully) the issue could be fixed by having the other plugin use an earlier hook, possibly `additional-chunk-assets` (?)

**Comment by jscheid** [comment]
See also #47

**Comment by arthurjamain** [comment]
Hey, 

Thanks for testing ! That's interesting, there might be more to it than appears at first glance. I still haven't switched back to this problematic, will keep you posted.

Cheers,

**Comment by arthurjamain** [comment]
Hey there !

So turns out I was as efficient as a drunk chipmunk would have been when first diagnosing this. I've opened a PR which is more on point than this discussion. Sorry for the derangement. https://github.com/waysact/webpack-subresource-integrity/pull/58
