### ISSUE TITLE
Puppeteer should be a dev dependency, not an optional dependency

### ISSUE THREAD

**Issue by ngyikp** [waysact/webpack-subresource-integrity#66]
Installing `webpack-subresource-integrity@1.1.0-rc.2` as a dependency would install Puppeteer unnecessarily and bloat node_modules size, Puppeteer should be included as a dev dependency instead.

**Comment by jscheid** [comment]
Thanks for the bug report. You're right, I'll change it and aim to release in 1.1.0-rc.3 sometime soon.

(Ideally it would be in "optional dev dependencies" but there is no such thing. https://github.com/npm/npm/issues/3870#issuecomment-219177596)
