### ISSUE TITLE
Hash is computed incorrectly when using mini-css-extract-plugin with CSS Modules

### ISSUE THREAD

**Issue by odensc** [waysact/webpack-subresource-integrity#68]
When using [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) with CSS Modules, the hash computed by the SRI plugin is incorrect causing an error. I'm assuming the hash is somehow calculated before `mini-css-extract-plugin` adds it's code.

**Comment by jscheid** [comment]
Thanks for the bug report. Could you provide a test project that shows the problem?

**Comment by odensc** [comment]
Sorry, I have bad manners. :) Here's a test case: https://github.com/odensc/sri-mini-repro

Instructions are in the readme.

**Comment by jscheid** [comment]
@odensc thanks again for the bug report and the repro, without it I couldn't have tracked it down. Fix for this is released in 1.1.0-rc.4.

**Comment by odensc** [comment]
@jscheid Thanks for the quick fix.

One more thing, it looks like the `integrity` attribute is not being added to the injected `link` element, as it would with `extract-text-webpack-plugin`. Would this be something on `mini-css-extract-plugin`'s side or this side?

**Comment by jscheid** [comment]
Ah, I see... I didn't realize `mini-css-extract-plugin` was doing DOM injection.

That's tricky, it will require coordination between the two plugins. I'm thinking about drafting a generic hook-based interface and running it by @sokra (the author of MCEP) to see what he thinks. I'm afraid it will take a little while and there's no easy workaround for now.

**Comment by jahed** [comment]
Matching thread for anyone wondering: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/40
