### ISSUE TITLE
stack-overflow in processChunkRecursive

### ISSUE THREAD

**Issue by SPSpwetter** [waysact/webpack-subresource-integrity#7]
Hints would be appreciated. Seems to be on the first chunk, which is a manifest chunk. Logging the chunk ids seems to show a loop.

**Comment by jscheid** [comment]
Could provide a test case or example project that demonstrates the issue?

**Comment by SPSpwetter** [comment]
Not yet. I'm trying to debug it but basically line 101 is vulnerable to a loop in the dependencies because the recursion will never finish. I'm trying to see if we did something to cause this loop. Hacking in a flag for already touched chunks prevents the crash.

**Comment by jscheid** [comment]
I'll have a look at this soon. It might be just a case of webpack not preventing circular dependencies, in which case it's just a matter of checking to see if the chunk has been visited before. It does sound like your project's dependencies are a bit wonky though.

**Comment by SPSpwetter** [comment]
I thought that at first and added a plugin and tried a tool and it says they're ok. Note that this is dependencies between chunks not files so I'm not sure how it's happening.

**Comment by SPSpwetter** [comment]
Reviewed the differences vs. master, and there was nothing wonky in the new dependencies that I could see.

**Comment by jscheid** [comment]
I've tried a few things:
- `file1` uses `require.ensure` to lazily load `file2`, and vice versa
- `file` lazy-loads `file2`, `file2` lazy-loads `file3`, `file3` lazy-loads `file1`
- `file1a` loads (eagerly) `file1b`, which lazily loads `file2`, which lazily loads `file1a`.

All of these work, so I'm not quite sure how to construct a test case.

I suppose we could add the flag for already touched chunks that you were mentioning, however I would really like to have a test case. Can you share your broken project? If you can't, can you distill it down to something that you can share?

**Comment by jscheid** [comment]
Also, what version of `webpack` and `webpack-core` are you using?

**Comment by SPSpwetter** [comment]
Yep, trying to figure out what caused this. I hacked in a log around the flag. It was someone else branch that merged in my SRI changes, so I'm sort of doing a binary search on require entries to see if figure out the loop. It's a loop between modules though, which all get funneled through a single router and some module definition files that have the synchronous require lines. I renamed all the module definition files I had into fooModule in case there was a name collision. 

I didn't know inter-chunk dependencies were possible, actually, except at the manifest, vendor, main, common chunk level. 

webpack is 1.13.1
webpack-core is 0.6.8

**Comment by SPSpwetter** [comment]
Interesting. The loop is because I have two modules: moduleA, and moduleB, that both think they depend on all the other modules plus one of each other. I'm wondering if this is a side effect of the CommonChunks plugin?

**Comment by SPSpwetter** [comment]
Found it, I had a file that was requiring the main entry file. That caused the loop. Though its interesting the build worked before that. Basically, we were getting away with it before because the file in that chunk required all the other chunks, but that worked out until I needed the file in two chunks.

**Comment by jscheid** [comment]
I'm glad it works for you now. Could you still help me reproduce this? I've tried a few more things with `CommonChunksPlugin` and multiple entry points but can't seem to cause an infinite recursion no matter what I try.

**Comment by SPSpwetter** [comment]
Sure. In the light of day I remember how it happened.  The problem is that my entry file also defines some global utilities. Normally they're loaded early. But in my Karma tests each test is its own unique entry file so it can't assume that the global are there. When the test was failing I added the entry file as a require to the file that needed the utilities rather than to the test because that made more sense in the moment as that's the normal habit. 

In the test that causes the global utilities to get loaded but in the production build its a short circuit because the require is already satisfied by the entry.  

It's all good until I had two chunks in the build referencing the same file. There might be interaction with the common chunks plugin as well, it's possible three chunks might have hosted the file into the common chunk.  

Though I assume now that you know this is possible you'll want to add a guard anyway and possibly a build warning.

**Comment by jscheid** [comment]
Fixed in df43b849ac12a5cffd5223298fa12223448b242c, published as 0.4.2.
