### ISSUE TITLE
Question: How to integrate it in webpack.config.js file?

### ISSUE THREAD

**Issue by shakiba** [waysact/webpack-subresource-integrity#70]
I may have missed a document somewhere, but how should I integrate this plugin in webpack.config.js file? I export one or an array of webpack configs, but I don't directly call `webpack()`.

**Comment by jscheid** [comment]
We have several [examples](https://github.com/waysact/webpack-subresource-integrity/tree/master/examples), a good starting point is probably [this one](https://github.com/waysact/webpack-subresource-integrity/blob/master/examples/basic/webpack.config.js).

**Comment by shakiba** [comment]
Thanks! I don't use Html plugin, I use webpack-assets-manifest. Is there any way to get integrity string values to add to manifest file?

**Comment by jscheid** [comment]
I don't know, I think that's more a question for the people looking after that plugin. I don't see an easy way but I haven't looked much.

Here is some code that you might find useful perhaps: https://github.com/jscheid/wsi-issue-45/blob/8dc86115bc788e3e2fb56a370159878ed1fbf4ea/webpack.config.babel.js#L19-L26

**Comment by shakiba** [comment]
Thanks, I wrote this to get it done:
```
var sriJsonPlugin = {
  apply: (compiler) => {
    compiler.plugin("done", stats => {
      // extract SRI values from compiler
      var assets = stats.compilation.assets;
      var newIntegrityMap = {};
      Object.keys(assets).forEach(key => {
        newIntegrityMap[key] = assets[key].integrity;
      });
      // load current SRI values from file
      var integrityFile = path.resolve(compiler.outputPath, 'integrity.json');
      var integrityJson;
      try {
        integrityJson = JsonFile.readFileSync(integrityFile);
      } catch (e) {
        integrityJson = {};
      }
      // merge them and write them back
      var newIntegrityJson = Object.assign({}, integrityJson, newIntegrityMap);
      integrityJson = JsonFile.writeFileSync(integrityFile, newIntegrityJson, {spaces: 2});
    });
  },
};
```

It would be great if we can add a similar basic option to this plugin!

**Comment by jscheid** [comment]
I suggest you ask the maintainers of the other plugin to include the original `asset` [here](https://github.com/danethurber/webpack-manifest-plugin/blob/052970ef91b9b319e0ba06772f2debf998e5a241/lib/plugin.js#L87) and [here](https://github.com/danethurber/webpack-manifest-plugin/blob/052970ef91b9b319e0ba06772f2debf998e5a241/lib/plugin.js#L102).

Then you could just do something like:

```js
new ManifestPlugin({ generate: (seed, files) => files.reduce(
    (manifest, { name, path, asset: { integrity } = {} }) => (
         { ...manifest, [name]: { path, integrity })
    ), seed) });
```
