### ISSUE TITLE
webpack 4.5 error - Cannot read property 'publicPath' of undefined

### ISSUE THREAD

**Issue by BartJanvanAssen** [waysact/webpack-subresource-integrity#75]
Hi all, 

In my custom webpack configuration i encounter some issues, regarding updating from webpack 3.x to 4.5 OR 4.4. Does anyone recognise the error or has any idea to get this fixed?

![image](https://user-images.githubusercontent.com/4742816/38984771-e1d8f884-43c7-11e8-855d-5a38ae04c0ec.png)

when i look at the code of this plugin i found the code is hitting over here:
![image](https://user-images.githubusercontent.com/4742816/38984925-56fe7774-43c8-11e8-978d-0ffc50920e77.png)

This error may come from other packages, however if i disable the SRi rule, the webpack build will succeed

Thanx, regards
Bart Jan

**Comment by jscheid** [comment]
Hi, please provide your `yarn.lock` or `package-lock.json` in a gist, or at least the versions of all relevant packages (webpack, html-webpack-plugin, this plugin).

**Comment by BartJanvanAssen** [comment]
Ah ofcource, here you go @jscheid 

`
{
"add-asset-html-webpack-plugin": "2.1.3",
 "html-webpack-plugin": "^3.2.0",
 "mini-css-extract-plugin": "^0.4.0",
 "webpack": "4.4.0",
 "webpack-cli": "2.0.14",
 "webpack-dev-server": "3.1.3",
 "webpack-subresource-integrity": "^1.1.0-rc.4"
`

**Comment by jscheid** [comment]
That's your `package.json`, I meant your lock file. From this I can only guess at what versions exactly you have installed.

Can you share your webpack config as well? Ideally you could make a repository that shows the problem.

**Comment by BartJanvanAssen** [comment]
i'll have a look if i can setup a basic project to simulate the issue, this takes a bit more time. Note i use for most packages the newest version. exception there for webpack. i'll let you know when i have it ready

**Comment by jscheid** [comment]
Ok thank you, much appreciated.

**Comment by zlk89** [comment]
Getting same error with webpack 4.6.0

**Comment by BartJanvanAssen** [comment]
I found that this plugin in combination with the AddAssetHtmlPlugin the argument to the beforeHtmlGeneration (pluginArgs) is an unfinished Promise. I need both, and have created an repo for this i'll post over here in a minute.

**Comment by BartJanvanAssen** [comment]
Repo is over here: with included steps to reproduce in the readme
https://github.com/BartJanvanAssen/Issue-Webpack-SRIPlugin-and-AddAsset

**Comment by jscheid** [comment]
As far as I can tell, this is caused by the other plugin registering a plugin that returns a Promise. I'll elaborate on the ticket over there.
